### ISSUE TITLE
SHIFT and CAPSLOCK don't work

### ISSUE THREAD

**Issue by tomrow** [hax0kartik/S3SH#2]
while SHIFT and CAPSLOCK change the characters displayed on the touch screen soft keyboard, they have no effect while typing, at least at the logon screen

**Comment by hax0kartik** [comment]
Fixed by commit https://github.com/hax0kartik/S3SH/commit/561d804cdd3b02b8fda397ac0447135ee7cf164a
Thanks for reporting!
